# AUTOGENERATED SPLIT: constants extracted from original file
# -*- coding: utf-8 -*-
# Tutaj wklejamy stałe/ustawienia 1:1.
# -----------------------------------
# Stałe / ustawienia
# -----------------------------------

SUPPORTED_EXTS = (".jpg", ".jpeg", ".png", ".webp")

# Modele i klucze konfiguracyjne
DEFAULT_OPENAI_MODEL = "gpt-5"  # multimodalny model (tekst + obraz) – dla OpenAI
DEFAULT_GEMINI_MODEL = "gemini-2.5-flash"
OPENAI_MODEL_FIELD = "openai_model"
GEMINI_MODEL_FIELD = "gemini_model"

# Pliki konfiguracyjne
PROMPTS_FILE = "prompts.json"   # w folderze programu
CONFIG_FILE = "config.json"     # w folderze programu

# Pola w config.json
OPENAI_API_KEY_FIELD = "openai_api_key"   # klucz OpenAI
GEMINI_API_KEY_FIELD = "gemini_api_key"   # NOWE: klucz Gemini
PROVIDER_FIELD = "provider"               # NOWE: "openai" | "gemini"
CAMERA_SAVE_PHOTOS_FIELD = "camera_save_photos"
CAMERA_PLAY_SOUND_FIELD = "camera_play_sound"
FOLLOWUP_PLAY_SOUND_FIELD = "followup_play_sound"
COMPARE_ATTACH_DESCRIPTIONS_FIELD = "compare_attach_descriptions"

# Zaawansowane opcje (konfiguracja limitów / wątków)
GPT_THREADS_FIELD = "gpt_threads"                 # liczba wątków dla GPT/OpenAI
GEMINI_RPM_FIELD = "gemini_rpm"                   # zapytań na minutę dla Gemini
GEMINI_BATCH_PAUSE_FIELD = "gemini_batch_pause_seconds"  # pauza między partiami (s)

# Domyślne wartości dla zaawansowanych opcji
DEFAULT_GPT_THREADS = 10
DEFAULT_GEMINI_RPM = 10
DEFAULT_GEMINI_BATCH_PAUSE_SECONDS = 60

# Inne
MAX_WORKERS = 10
