# -*- coding: utf-8 -*-
# AUTOGENERATED SPLIT: exif_io (izoluje zależność od piexif)
# Nic nie zmieniamy w logice, tylko trzymamy wszystko związane z EXIF tutaj.
import os
try:
    import piexif
    PiexifOK = True
except ImportError:
    PiexifOK = False

from PIL import Image, PngImagePlugin

# -----------------------------------
# EXIF zapisywanie/odczyt dla JPG
# -----------------------------------
def _to_utf16le_bytes(text: str) -> bytes:
    return text.encode("utf-16le") + b"\x00\x00"

def add_description_to_jpg(image_path: str, description: str):
    if not PiexifOK:
        return
    try:
        try:
            exif_dict = piexif.load(image_path)
        except Exception:
            exif_dict = {"0th": {}, "Exif": {}, "1st": {}, "GPS": {}, "Interop": {}, "thumbnail": None}

        exif_dict["0th"][piexif.ImageIFD.ImageDescription] = description.encode("utf-8", errors="ignore")
        exif_dict["0th"][piexif.ImageIFD.XPTitle]   = _to_utf16le_bytes(description)
        exif_dict["0th"][piexif.ImageIFD.XPSubject] = _to_utf16le_bytes(description)

        exif_bytes = piexif.dump(exif_dict)
        piexif.insert(exif_bytes, image_path)
    except Exception as e:
        print(f"[UWAGA EXIF] Nie udało się zapisać opisu do {os.path.basename(image_path)}: {e}")

def read_description_from_jpg(image_path: str):
    if not PiexifOK:
        return None
    try:
        exif_dict = piexif.load(image_path)
        raw = exif_dict["0th"].get(piexif.ImageIFD.ImageDescription)
        if raw:
            try:
                return raw.decode("utf-8", errors="ignore").strip()
            except Exception:
                return str(raw)
    except Exception:
        pass
    return None

def remove_description_from_jpg(image_path: str):
    if not PiexifOK:
        return
    try:
        exif_dict = piexif.load(image_path)
        for tag in (piexif.ImageIFD.ImageDescription, piexif.ImageIFD.XPTitle, piexif.ImageIFD.XPSubject):
            if tag in exif_dict["0th"]:
                del exif_dict["0th"][tag]
        exif_bytes = piexif.dump(exif_dict)
        piexif.insert(exif_bytes, image_path)
    except Exception as e:
        print(f"[UWAGA EXIF] Nie udało się usunąć opisu z {os.path.basename(image_path)}: {e}")

# -----------------------------------
# Metadane dla PNG
# -----------------------------------
_PNG_TEXT_KEYS_ORDER = ["Description", "Comment", "Title", "Subject"]

def _png_read_text(path: str) -> dict:
    try:
        with Image.open(path) as im:
            return dict(im.info or {})
    except Exception:
        return {}

def read_description_from_png(path: str):
    info = _png_read_text(path)
    for k in _PNG_TEXT_KEYS_ORDER:
        v = info.get(k) or info.get(k.lower())
        if isinstance(v, str) and v.strip():
            return v.strip()
    return None

def add_description_to_png(path: str, text: str):
    with Image.open(path) as im:
        meta = PngImagePlugin.PngInfo()
        for k, v in (im.info or {}).items():
            if isinstance(v, str):
                meta.add_text(k, v)
        meta.add_text("Description", text)
        meta.add_text("Title", text)
        meta.add_text("Subject", text)
        im.save(path, pnginfo=meta)

def remove_description_from_png(path: str):
    with Image.open(path) as im:
        meta = PngImagePlugin.PngInfo()
        for k, v in (im.info or {}).items():
            if isinstance(v, str) and k.lower() not in ("description", "title", "subject", "comment"):
                meta.add_text(k, v)
        im.save(path, pnginfo=meta)

# -----------------------------------
# API uniwersalne
# -----------------------------------
def add_description(image_path: str, description: str):
    ext = os.path.splitext(image_path)[1].lower()
    if ext in (".jpg", ".jpeg"):
        return add_description_to_jpg(image_path, description)
    if ext == ".png":
        return add_description_to_png(image_path, description)
    return None

def read_description(image_path: str):
    ext = os.path.splitext(image_path)[1].lower()
    if ext in (".jpg", ".jpeg"):
        return read_description_from_jpg(image_path)
    if ext == ".png":
        return read_description_from_png(image_path)
    return None

def remove_description(image_path: str):
    ext = os.path.splitext(image_path)[1].lower()
    if ext in (".jpg", ".jpeg"):
        return remove_description_from_jpg(image_path)
    if ext == ".png":
        return remove_description_from_png(image_path)
    return None
